### ISSUE TITLE
Encoding Exception

### ISSUE THREAD

**Issue by erwanlr** [darryllane/Bluto#11]
Sometimes during the data mining process, an encoding issue is raised and Bluto hangs up and has to be killed:
```
Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
 File "/usr/lib/python2.7/threading.py", line 505, in run
   self.__target(*self.__args, **self.__kwargs)
 File "/usr/local/lib/python2.7/dist-packages/Bluto/modules/data_mine.py", line 208, in doc_start
   download_list = action_download(doc_list, docs)
 File "/usr/local/lib/python2.7/dist-packages/Bluto/modules/data_mine.py", line 61, in action_download
   temp = str(doc).rsplit('.', 1)[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 77: ordinal not in range(128)
```

**Comment by darryllane** [comment]
This should now be resolved, along with the couple of issues you raised offline. Please upgrade, and thanks for the feedback
