### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by rapilo** [darryllane/Bluto#12]
I ran this on Kali 2016.1 (pip 9.0.1) and Parrot OS 3.3 (pip 8.1.2)  and always receive the same error. This is with API and without (just domain). 

Brute Forcing Sub-Domains

	While you are waiting we will gather email addresses
	and LinkedIn users

Gathering Data From Google, Bing And LinkedIn
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 189, in <module>
    userCountry, userServer = action_country_id(COUNTRIES_FILE, prox)
  File "/usr/local/lib/python2.7/dist-packages/Bluto/modules/general.py", line 144, in action_country_id
    r = requests.get(r'https://freegeoip.net/json/')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

**Comment by darryllane** [comment]
Oo this is a new one, ill take a look. Thanks for letting me know

**Comment by darryllane** [comment]
Could I ask what country this is from, so I can test from that location (hopefully)

**Comment by darryllane** [comment]
Can you upgrade and confirm if this is still a problem?
