### ISSUE TITLE
Can not install Bluto on OSX el captian and above.

### ISSUE THREAD

**Issue by battletux** [darryllane/Bluto#13]
Not sure if this needs to be mentioned in the install logs for OS X users or not but I ran into an issue installing it on OSX Sierra.

When running `sudo pip install git+git://github.com/darryllane/Bluto` I was getting the following error:

`Installing collected packages: six, cryptography, pyOpenSSL
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-Nmy30E-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

After some digging it seems to be an issue with OS X's System integrity protection. The answer to the issue I found [here](https://github.com/pypa/pip/issues/3165)

To install successfully on OSX El Captain and above I needed to add the `--ignore-installed` switch:

`sudo pip install --ignore-installed git+git://github.com/darryllane/Bluto`

This allows the install to complete and bluto to run successfully.

**Comment by darryllane** [comment]
Hi, I can't recall if I had a similar problem when I upgraded to El
captian. I think it's a good issue to add to an FAQ maybe. Thanks for the
contribution, I'll fire up the wiki over the weekend.

**Comment by erwanlr** [comment]
Same when updating ;)

Also had to manually install ```docopt``` with pip

**Comment by darryllane** [comment]
Erwan did you update via the update function(beta) or directly via 'pip install bluto --upgrade' or via the old method?

**Comment by erwanlr** [comment]
Via pip: ```sudo pip install git+git://github.com/darryllane/Bluto --upgrade```

**Comment by darryllane** [comment]
Ok, i need to update the docs as thats deprecated. Although it should still work, ill take a look tonight. Thanks again for the feedback
