### ISSUE TITLE
when i run bluto

### ISSUE THREAD

**Issue by m4d3bug** [darryllane/Bluto#18]
the system just return this meassage to me
bluto 

Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 56, in <module>
    from modules.get_dns import action_brute_start, action_wild_cards, action_zone_transfer, get_dns_details, action_brute_wild, set_resolver

ImportError: No module named get_dns

how can i fix this?

**Comment by darryllane** [comment]
Hi, could you attempt to uninstall and reinstall via
Sudo pip uninstall bluto
Sudo pip install bluto

If that doesnt resolve it can you let me know what version of python and what OS your running please

**Comment by m4d3bug** [comment]
the python should be 2.7.14 or higher or just fit in python3 ?

**Comment by darryllane** [comment]
This version of bluto should be 2.7.x it doesnt work with =< 3

**Comment by m4d3bug** [comment]
when i run pip install bluto the return like this:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'


and i run pip3 install bluto the return like this:
Collecting bluto
  Downloading Bluto-2.4.6.tar.gz (873kB)
    100% |████████████████████████████████| 880kB 296kB/s 
Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.6/dist-packages (from bluto)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from bluto)
Collecting docopt (from bluto)
  Downloading docopt-0.6.2.tar.gz
Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (from bluto)
Collecting oletools (from bluto)
  Downloading oletools-0.52.2.zip (1.7MB)
    100% |████████████████████████████████| 1.7MB 162kB/s 
Collecting pdfminer (from bluto)
  Downloading pdfminer-20140328.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 68kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7_shiztj/pdfminer/setup.py", line 3, in <module>
        from pdfminer import __version__
      File "/tmp/pip-build-7_shiztj/pdfminer/pdfminer/__init__.py", line 5
        print __version__
                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7_shiztj/pdfminer/



by the way,my python 2 is 
Python 2.7.14+ (default, Feb  6 2018, 19:12:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
my python3 is 
Python 3.6.4+ (default, Feb 12 2018, 08:25:03) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by darryllane** [comment]
The first error looks like a timeout, the second is because pip3 uses python3. This version of bluto is not compatible with python3 that includes the versions of libs it uses as dependents.

What OS and distro are you running on? I would suggest using virtualenv for your tools dude.

**Comment by ImBharathwaj** [comment]
I've installed bluto from pip3 in parrot os
I couldn't run it properly. 
first It was showing print syntax error for python2 presence instead of python3
Then I changed the whole script into python3 
Still it shows error like this 
`Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 48, in <module>
    from modules.get_dns import action_brute_start, action_wild_cards, action_zone_transfer, get_dns_details, action_brute_wild, set_resolver
  File "/usr/local/lib/python3.9/dist-packages/Bluto/modules/get_dns.py", line 11, in <module>
    from bluto_logging import info, INFO_LOG_FILE
ModuleNotFoundError: No module named 'bluto_logging'
`
I changed the whole script of bluto_logging after referring github
Still, I couldn't make it run

**Comment by darryllane** [comment]
It's a python 2.7 app it doesn't work in 3
