### ISSUE TITLE
Error when running latest dev 

### ISSUE THREAD

**Issue by baditaflorin** [darryllane/Bluto#24]
ZoneTranfer Check:

Exception in thread Brute:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Bluto/modules/execute.py", line 264, in zone
    z = dns.zone.from_xfr(dns.query.xfr(ns, domain, timeout=10, lifetime=10))
  File "/usr/local/lib/python3.5/dist-packages/dns/zone.py", line 1066, in from_xfr
    for r in xfr:
  File "/usr/local/lib/python3.5/dist-packages/dns/query.py", line 490, in xfr
    "No answer or RRset not for qname")
dns.exception.FormError: No answer or RRset not for qname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Bluto/modules/b_classes/class_calls.py", line 128, in enumerate_subdomains
    obj._brute()
  File "/usr/local/lib/python3.5/dist-packages/Bluto/modules/execute.py", line 401, in _brute
    self.zone()
  File "/usr/local/lib/python3.5/dist-packages/Bluto/modules/execute.py", line 301, in zone
    except dns.query.TransferError:
AttributeError: module 'dns.query' has no attribute 'TransferError'

**Comment by darryllane** [comment]
Thanks for reporting, ill take a look

**Comment by darryllane** [comment]
Arr this on dev branch, I have a huge update for dev. In fact I wont be updating dev until the new html reporting module is completed. I have been dragging my heels with it, ill try get a release out in the next week or so.

**Comment by ArujReis** [comment]
Hey, it seems that the last dev update broke some things because of missing files/modules (like `b_modules/fake_useragent.py` and `html_report_BETA.py` (maybe more, but I didn't dwell into it that deep).

Just heads up.

**Comment by darryllane** [comment]
Thanks for reporting. I will push and update tonight

**Comment by darryllane** [comment]
Dev is going to be broken a lot though as its bleeding. But by all means please keep reporting any issues you find.
