### ISSUE TITLE
Latest version of PDFMiner causes errors.

### ISSUE THREAD

**Issue by jkraus-net** [darryllane/Bluto#25]
The latest version of PDFMiner (20191010) causes the following error:

Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 53, in <module>
    from modules.data_mine import doc_start
  File "/usr/local/lib/python2.7/dist-packages/Bluto/modules/data_mine.py", line 17, in <module>
    from pdfminer.pdfparser import PDFParser
  File "/home/Deneir/.local/lib/python2.7/site-packages/pdfminer/pdfparser.py", line 4, in <module>
    from .psparser import PSStackParser
  File "/home/Deneir/.local/lib/python2.7/site-packages/pdfminer/psparser.py", line 4, in <module>
    from .utils import choplist
  File "/home/Deneir/.local/lib/python2.7/site-packages/pdfminer/utils.py", line 219, in <module>
    0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
  File "/home/Deneir/.local/lib/python2.7/site-packages/pdfminer/utils.py", line 187, in <genexpr>
    PDFDocEncoding = ''.join(chr(x) for x in (
ValueError: chr() arg not in range(256)

Installing the previous release resolves it.

**Comment by darryllane** [comment]
Can you recall the specific version number? Ill make sure the requirments reflect the version.

**Comment by jkraus-net** [comment]
Version 20140328.  PDFMiner released a new version earlier today (20191016), haven't had a chance to test with it yet.

**Comment by darryllane** [comment]
Ok released a post release to resolve the problem. Thanks again, ill leave this open for a day or two. Let me know any feedback and ill close accordingly 

pip2.7 install bluto --upgrade
