### ISSUE TITLE
Error when installing Bluto

### ISSUE THREAD

**Issue by unraveller82** [darryllane/Bluto#37]
Hi,

I am unable to install Bluto.

I am currently using Kali Linux
error message:
==========================================================
Downloading/unpacking pyparsing>=2.1.0 (from oletools->bluto)
  Running setup.py egg_info for package pyparsing
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/kali/week4/build/pyparsing/setup.py", line 10, in <module>
        from pyparsing import __version__ as pyparsing_version
      File "pyparsing/__init__.py", line 104, in <module>
        from pyparsing.core import __diag__, __compat__
      File "pyparsing/core.py", line 166
        nonlocal found_arity, limit
                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/kali/week4/build/pyparsing/setup.py", line 10, in <module>

    from pyparsing import __version__ as pyparsing_version

  File "pyparsing/__init__.py", line 104, in <module>

    from pyparsing.core import __diag__, __compat__

  File "pyparsing/core.py", line 166

    nonlocal found_arity, limit

                       ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/kali/week4/build/pyparsing
Storing complete log in /root/.pip/pip.log

==========================================================

when i run bluto command:
====================================================
bluto
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 4, in <module>
    __import__('pkg_resources').run_script('Bluto==2.4.17', 'bluto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing>=2.1.0' distribution was not found and is required by oletools

====================================================

**Comment by darryllane** [comment]
Can you confirm the python version you are using please

**Comment by unraveller82** [comment]
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.1"
VERSION_ID="2020.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
kali@kali:~/flunym0us2.0$

**Comment by unraveller82** [comment]
its ok now. I reinstall pip and it works

**Comment by darryllane** [comment]
Thanks for letting me know.
